### ISSUE TITLE
Could not use the plugin with Grails 3

### ISSUE THREAD

**Issue by Leward** [puneetbehl/grails-jasper#1]
Hellow I tried to add the plugin to my build.gradle without any success. I tried the following: 

```
compile "org.grails.plugins:jasper:2.0.0.RC1"
compile "org.grails.plugins:jasper:v2.0.0.RC1"
```

None of them work. 

Ther plugin cannot be located there: https://repo.grails.org/grails/core/org/grails/plugins/ 

What is the proper configuration? Is it possible to have it added to the documentation? 

Regards, 
Paul-Julien

**Comment by puneetbehl** [comment]
Yes, creating documentation is in my todo list but meanwhile can you please try again with following

``` groovy
compile "org.grails.plugins:jasper:2.0.0.RC1"
```

**Comment by Leward** [comment]
This works now. Thank you very much.

**Comment by andreasschiestl** [comment]
@puneetbehl  Is there any additional config required? I get the following error if I add the dependency you recommended

> Error:Could not find org.grails.plugins:jasper:2.0.0.RC1.
> Searched in the following locations:
>     file:/Users/andreasschiestl/.m2/repository/org/grails/plugins/jasper/2.0.0.RC1/jasper-2.0.0.RC1.pom
>     file:/Users/andreasschiestl/.m2/repository/org/grails/plugins/jasper/2.0.0.RC1/jasper-2.0.0.RC1.jar
>     https://repo.grails.org/grails/core/org/grails/plugins/jasper/2.0.0.RC1/jasper-2.0.0.RC1.pom
>     https://repo.grails.org/grails/core/org/grails/plugins/jasper/2.0.0.RC1/jasper-2.0.0.RC1.jar
> Required by:
>     businesssuite:businesssuite:0.3-dev

**Comment by andreasschiestl** [comment]
When I add `maven { url "http://dl.bintray.com/puneetbehl/plugins" }` to the repositories in the build.gradle everything works as expected.

This is a little bit weird. Is it possible to publish the plugin in the grails repo at https://repo.grails.org/grails/core or at least at http://dl.bintray.com/grails/plugins (Note that the jasper plugin is published in this repo but unter http://dl.bintray.com/grails/plugins/2.0.0.RC1/ instead of http://dl.bintray.com/grails/plugins/org/grails/plugins/jasper/2.0.0.RC1/)
